src/diracx/routers/auth.py
src/diracx/routers/configuration.py
src/diracx/routers/dependencies.py
src/diracx/routers/job_manager/__init__.py
src/diracx/routers/well_known.py

This makes it possible to set the type of route arguments to `Config`/`AuthSettings`/`JobDB` without needing to specify the annotation on every route.

Move router dependencies to a submodule

---

.github/workflows/deployment.yml
.github/workflows/make_release.py
LICENSE
environment.yml
release.notes
setup.cfg
src/diracx/__init__.py

This was tested here https://github.com/chaen/diracx/actions/runs/5797008925/job/15711715092 against the test pypi
Hopefully, this will work right away
It is based on what is done for the rest of the DIRAC ecosystem, except:
* it only accepts pre-releases for now
* uses trusted-publisher for pypi
* release notes are just git diff 
Depending on the dev strategy we will decide (https://github.com/DIRACGrid/diracx/discussions/60), we can consider existing tools to help us in various tasks (for example https://github.com/x-motemen/git-pr-release)

Automatic release CI

---

src/diracx/routers/fastapi_classes.py
src/diracx/routers/job_manager/__init__.py

- FastAPI 0.99.0 is using openapi 3.1.0 by default: https://fastapi.tiangolo.com/release-notes/?h=0.99.0#features_3
- Autorest does not support it yet
```bash
error   | schema_violation | Schema violation: must match pattern "^3\.0\.\d(-.+)?$" (openapi)
pattern: ^3\.0\.\d(-.+)?$
- file:///tmp/pytest-of-aldbr/pytest-49/test_regenerate_client0/openapi.json:1:2
```

"Freeze" the openapi version to 3.0.2

---

src/diracx/routers/job_manager/__init__.py
tests/routers/test_job_manager.py

Adding bulk submission of jdls to the job submission endpoint, and implement job policy checking (solves  Implement JobPolicy #23 )
(Tests need to be relaunched once https://github.com/DIRACGrid/DIRAC/pull/7092 get merged)

feat: adding bulk jdl submission and job policy checking

---

.pre-commit-config.yaml
setup.cfg
src/diracx/db/__init__.py
src/diracx/db/sandbox_metadata/db.py
src/diracx/db/sandbox_metadata/schema.py
tests/conftest.py
tests/db/test_sandboxMetadataDB.py

This PR adds the basic functionalities of SandboxMetadataDB. Partially addresses https://github.com/DIRACGrid/diracx/issues/13 . Few notes:
- the DB schema added here is what is defined in https://github.com/DIRACGrid/DIRAC/pull/6566 (so, what is in DIRAC v8.1 but excluding OwnerDN).
- Only insertion of a new SB is added, no other functionalities (deletion is tentatively added)
- There are discussions going on in https://github.com/DIRACGrid/diracx/discussions/16 that might lead to a simplification of DIRAC's Sandbox (specifically if external Sandbox SEs are not supported) so I would wait before implementing further.

Partially adding sandbox metadata db

---

src/diracx/db/__main__.py
src/diracx/db/utils.py
src/diracx/routers/__init__.py
tests/conftest.py
tests/db/auth/test_authorization_flow.py
tests/db/auth/test_device_flow.py
tests/db/auth/test_refresh_token.py
tests/db/jobs/test_jobDB.py
tests/db/jobs/test_jobLoggingDB.py
tests/db/test_dummyDB.py
tests/db/test_sandboxMetadataDB.py

When running in production we don't want to be filling the DB schema everytime the engine is created.
This PR:
* Adds a new classmethod `available_implementations` to `BaseDB` that retrieves available implementations for a given database name.
* Adds a `__main__` module to `diracx.db` such that the databases can be initialised with something like `python -m diracx.db init-sql`

Separate creating the DB schema from the engine creation

---

.github/workflows/main.yml
codecov.yml
docs/README.md
tests/conftest.py
tests/db/opensearch/conftest.py
tests/db/opensearch/test_connection.py

This PR makes it possible to pass `--demo-dir ../diracx-charts/` to pytest to run enhanced tests. For now this is just used to test against OpenSearch however it should soon be expanded to include MySQL and the DiracX services themselves. Doing that might result in the fixtures being refactored but the I think the interface for running the tests will be stable.
In general these tests should focus on being independent, fast and easy to rerun without leaving any messy state on the server. In the case of testing against OpenSearch I create a random index prefix each time and try to clean up again afterwards (but even if the cleanup fails future test runs should be unaffected).
Whil the standard `pytest` job is a strict subset, I keep it as I think we should keep the CI for the sake of making …

Support running enchanced tests against the demo instance

---

src/diracx/core/models.py
src/diracx/routers/auth.py

In Python 3.11 a `StrEnum` class was added to avoid some of the issues with inheriting from `str`. See https://github.com/python/cpython/issues/85982 for details.

Use StrEnum instead of subclassing both str and Enum

---

src/diracx/core/models.py
src/diracx/routers/auth.py
src/diracx/routers/job_manager/__init__.py

I have some use cases for `UserInfo` outside of the services where the `AuthInfo` part isn't needed. I suggest we rename it to `AuthorizedUserInfo` and move the mixin to `diracx.core.models`.

Split UserInfo so it can be used in diracx.core

---

.github/workflows/integration.yml
src/diracx/client/_patch.py
src/diracx/client/aio/_patch.py
src/diracx/core/config/schema.py
src/diracx/core/utils.py
src/diracx/routers/auth.py
tests/routers/auth/test_legacy_exchange.py
tests/routers/auth/test_standard.py

Needs https://github.com/DIRACGrid/DIRAC/pull/7222

Add /auth/legacy-exchange

---

src/diracx/routers/job_manager/sandboxes.py
tests/routers/jobs/test_sandboxes.py

This keeps the existing DIRAC behaviour, though in practice we rely on being able to use the webapp to bypass this restriction. It should probably follow the job policy logic.
Needs https://github.com/DIRACGrid/diracx/pull/117

Prevent users from downloading each other's sandboxes

---

src/diracx/db/sql/jobs/schema.py
src/diracx/db/sql/sandbox_metadata/db.py
src/diracx/db/sql/utils.py
src/diracx/routers/auth.py
src/diracx/routers/job_manager/sandboxes.py
tests/conftest.py
tests/db/test_sandbox_metadata.py
tests/routers/jobs/test_sandboxes.py

See the commit messages for details.

Fixes for getting DiracX installed on lbcertifidirac70

---

src/diracx/__init__.py
src/diracx/cli/internal/legacy.py
tests/cli/legacy/cs_sync/integration_test.cfg
tests/cli/legacy/cs_sync/integration_test_secret.cfg
tests/cli/legacy/test_legacy.py

For #125 
It gives the initial values.yaml alright for the dirac setup running on openshift, but we will have to polish the ingress and SNI for running everything on k3s or other before being able to generate a fully correct initial values.yaml

Starting point for "dirac internal legacy generate-helm-values"

---

run_local.sh
tests/make-token-local.py

This makes it so that when you execute `./run_local.sh` you get:
```
DiracX is running on http://localhost:8000
To interact with DiracX you can:
1. Use the CLI:
export DIRACX_URL=http://localhost:8000
tests/make-token-local.py /var/folders/1g/q2y74s696ng0v_cmb9sv7qgr0000gn/T/tmp.CJ4d9L9H/signing-key/rsa256.key
2. Using swagger: http://localhost:8000/api/docs
```
Using `tests/make-token-local.py` gives you a token which is valid for a week.

Make run_local.sh usable

---

.github/workflows/containerised.yml

It should get better when we have a base image cached, but it anyway doesn't hurt

Add a default 30mn timeout for the container build

---

diracx-cli/src/diracx/cli/internal/__init__.py
diracx-cli/tests/test_internal.py
run_local.sh

Would this make sense?
It would allow setting up multiple VOs and groups when launching `diracx` with `run_demo` (of course we would need another PR in `diracx-charts`).
- The alternative is to manually change the config (`default.yml`) and commit it from a running pod (which is probably fine too).

feat: internals `add_vo()` and `add_group()`

---

.github/workflows/make_release.py
README.md
containers/client/Dockerfile
containers/services/Dockerfile
diracx-cli/src/diracx/cli/__init__.py
diracx-routers/src/diracx/routers/auth/utils.py
pyproject.toml

Add the Bandit check in `ruff`.
These are basically best practices to avoid obvious security loophole. It comes with quite some false positive, but it is better than false negative when it comes to security :-)

test: bandit CI

---

diracx-core/pyproject.toml
diracx-routers/pyproject.toml

DIRAC integration tests are timing out because each `pip install` takes 10 mn because of that

Set minimal version of aiobotocore to speedup pip resolution

---

diracx-cli/src/diracx/cli/utils.py
diracx-client/src/diracx/client/_patch.py
diracx-client/src/diracx/client/aio/_patch.py
diracx-routers/src/diracx/routers/auth/management.py
diracx-routers/src/diracx/routers/auth/token.py
diracx-routers/src/diracx/routers/auth/utils.py
diracx-routers/tests/auth/test_legacy_exchange.py
diracx-routers/tests/auth/test_standard.py
diracx-routers/tests/test_config_manager.py

Aims at fixing the following error:
```bash
$ dirac login diracAdmin
$ dirac jobs submit job.jdl
RuntimeError: An issue occured while refreshing your access token: Invalid JWT: bad_signature:
$ dirac login diracAdmin
RuntimeError: An issue occured while refreshing your access token: Invalid JWT: bad_signature:
$ dirac logout
$ dirac login diracAdmin
```
In this PR, we check the validity of the refresh token before refreshing the access token. We should have:
```bash
$ dirac login diracAdmin
$ dirac jobs submit job.jdl
HttpResponseError: Operation returned an invalid status 'Forbidden'
Content: {"detail":"Not authenticated"}
$ dirac login diracAdmin
```

fix(client): better error when refresh token is expired

---

diracx-routers/pyproject.toml
diracx-routers/src/diracx/routers/__init__.py
diracx-routers/src/diracx/routers/access_policies.py
diracx-routers/src/diracx/routers/auth/__init__.py
diracx-routers/src/diracx/routers/auth/authorize_code_flow.py
diracx-routers/src/diracx/routers/auth/device_flow.py
diracx-routers/src/diracx/routers/auth/management.py
diracx-routers/src/diracx/routers/auth/token.py
diracx-routers/src/diracx/routers/auth/utils.py.orig
diracx-routers/src/diracx/routers/auth/well_known.py
diracx-routers/src/diracx/routers/configuration.py
diracx-routers/src/diracx/routers/job_manager/__init__.py
diracx-routers/src/diracx/routers/job_manager/access_policies.py
diracx-routers/src/diracx/routers/job_manager/sandboxes.py
diracx-routers/src/diracx/routers/utils/users.py
diracx-routers/tests/auth/test_legacy_exchange.py
diracx-routers/tests/auth/test_standard.py
diracx-routers/tests/jobs/test_sandboxes.py
diracx-routers/tests/jobs/test_wms_access_policy.py
diracx-routers/tests/test_config_manager.py
diracx-routers/tests/test_generic.py
diracx-routers/tests/test_job_manager.py
diracx-routers/tests/test_policy.py
diracx-testing/src/diracx/testing/__init__.py
docs/README.md
docs/TESTING.md
tests/make-token-local.py

Linked to https://github.com/DIRACGrid/diracx/issues/161
needs https://github.com/tiangolo/fastapi/pull/11355

Policy Mechanism

---

diracx-client/src/diracx/client/_patch.py

Without this, if defining the server URL like `export DIRACX_URL=https://diracx-cert.app.cern.ch/` (note the trailing `/`), we get an exception when doing `dirac login`

use urljoin instead of string manipulation

---

diracx-db/src/diracx/db/os/utils.py

This was a stupid bug which just prevented 2 calls in a row on an OS DB :man_shrugging:

Do not close the connection to OS DB when finishing a request

---

diracx-core/src/diracx/core/models.py
diracx-routers/tests/jobs/test_sandboxes.py

The OpenAPI document contains an incorrect example for the `checksum` field in the `POST /sandbox` route. 
It was generated from the `SandboxInfo` pydantic model, where the pattern was not correct.
As the default `checksum_algorithm` is `sha256`, the `checksum` should be a 64-character hexadecimal string composed only of the characters 0-9, a-f, or A-F.

fix(jobs): malformed checksum error when uploading a sandbox

---

diracx-cli/pyproject.toml
diracx-cli/src/diracx/cli/jobs.py
diracx-cli/tests/test_jobs.py

Closes https://github.com/DIRACGrid/diracx/issues/280
More details in https://github.com/fastapi/typer/discussions/943 (update: they won't solve the issue because we actually relied on a bug rather than a feature. So I adjusted our code accordingly)

fix(diracx-cli): adapt `jobs` cli to resolve issue with typer >= 0.12.4

---

diracx-routers/tests/auth/test_standard.py

pytest_httpx made a release today that screwed up our tests. 
Fix it 
https://github.com/Colin-b/pytest_httpx/blob/develop/CHANGELOG.md#0320---2024-09-27

Adapt tests to pytest_httpx >= 0.32.0

---

diracx-routers/src/diracx/routers/auth/token.py
diracx-routers/src/diracx/routers/auth/utils.py
diracx-routers/src/diracx/routers/utils/users.py
diracx-routers/tests/auth/test_legacy_exchange.py
diracx-routers/tests/auth/test_standard.py
diracx-testing/src/diracx/testing/__init__.py

Closes https://github.com/DIRACGrid/diracx/issues/148
Use cases (scope we provide to the `auth` endpoints :arrow_right: claims we should obtain from the token)
- `<vo>` :arrow_right: `<vo> <default group> <properties of default group>`
- `<vo> <group>` :arrow_right: `<vo> <group> <properties of group>`
- `<vo> <properties>` :arrow_right: `<vo> <default group> <properties of default group + properties>`
- `<vo> <group> <properties>` :arrow_right: `<vo> <group> <properties of group + properties>`

feat: allow to request specific properties when logging in

---

diracx-cli/src/diracx/cli/__init__.py
diracx-routers/src/diracx/routers/auth/authorize_code_flow.py
diracx-routers/src/diracx/routers/auth/device_flow.py

Add documentation about the scope following https://github.com/DIRACGrid/diracx/pull/300
The same string is repeated at 3 different locations in the code. While it is cumbersome (developers would need to update every instances of the doc to avoid any discrepancy, which will likely happen at some point), I don't see any other way of doing that as openapi reads the static documentation and I find it convenient to have the details when using the CLI or the openapi document.
Any opinion?

feat(auth): add scope documentation

---

diracx-testing/src/diracx/testing/__init__.py

httpx 0.28.0 has ome API breaking changes with the `verify` flag, so adapt to it
https://github.com/encode/httpx/releases/tag/0.28.0

Fix for httpx 0.28.0

---

diracx-core/pyproject.toml
diracx-core/src/diracx/core/config/__init__.py
pyproject.toml

Closes https://github.com/DIRACGrid/diracx/issues/319

use sh.git instead of git module

---

.github/workflows/vulnerabilities.yml

Closes https://github.com/DIRACGrid/diracx/issues/321
This PR adds a github action workflow that scans the docker image once per week:
- it tries to find known vulnerabilities in the dependencies of the dev and release images (`client`, `services`)
- if any vulnerability is found, it adds a sarif report within the Security tab of the repo
If we want to use `trivy` we need to enable the `CodeQL-Analysis` tool in the Security tab of the repo first.
Example: https://github.com/aldbr/diracx/actions/runs/12054468700/job/33612561588
Do you have any opinion about such a tool? Any comment?

feat(github): test scanning vulnerabilities with trivy

---

diracx-cli/src/diracx/cli/__init__.py
diracx-client/src/diracx/client/patches/aio/utils.py
diracx-client/src/diracx/client/patches/utils.py
diracx-client/tests/test_auth.py
diracx-core/src/diracx/core/utils.py
diracx-core/tests/test_utils.py

closes #133
Tests can be performed on `read/write_credentials`, and the client (probably simpler if we do it through `get_token` directly). Test cases:

feat: lock file while read, write and refresh token

---

diracx-testing/src/diracx/testing/__init__.py

Create a pytest fixture to notify devs when entry-points in the environment and the one in pyproject are not consistent.
Closes #152

test: pytest fixture to notify changes in entry-points

---

diracx-core/src/diracx/core/config/sources.py
diracx-core/tests/test_config_source.py

feat: overriding default git branch in remote config source

---

diracx-db/src/diracx/db/sql/auth/schema.py

Oops :sweat_smile: 
```bash
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'AuthorizationFlows.CretionTime' in 'where clause'")
```

fix(diracx-db): AuthDB column typo

---

diracx-cli/src/diracx/cli/auth.py
diracx-client/pyproject.toml
diracx-client/src/diracx/client/generated/_patch.py
diracx-client/src/diracx/client/patches/utils.py
diracx-core/tests/test_s3.py
diracx-routers/pyproject.toml
diracx-routers/tests/jobs/test_sandboxes.py
diracx-testing/pyproject.toml
diracx-testing/src/diracx/testing/utils.py
extensions/gubbins/gubbins-client/pyproject.toml
extensions/gubbins/gubbins-routers/pyproject.toml

Notes for reviewers:
* The `get_openid_config` seems to be not covered by tests, see 55522d5
* requests was imported in the patch file for the autogenerated client code, but marked as not used. See [7de3db1](https://github.com/DIRACGrid/diracx/pull/374/commits/7de3db13b7f01ca86b8eba9de038f9e7849f1cfc)
* The async client uses the sync `get_openid_config`, should probably be using its own async version
Fixes #338

Requests → httpx

---

diracx-routers/src/diracx/routers/jobs/query.py

- The current code currently reflects the behavior we want to have once the migration will be over, but it cannot work as of now.
- We still have to deal with the `preferred_username` field, so this PR temporarily solves the issue. 
More details are explained in https://github.com/DIRACGrid/diracx/issues/385

fix(diracx-routers): search endpoint does not display jobs in GlobalMonitoring is set to False

---

diracx-core/src/diracx/core/exceptions.py
diracx-db/src/diracx/db/sql/sandbox_metadata/db.py
diracx-routers/src/diracx/routers/jobs/sandboxes.py
diracx-routers/tests/jobs/test_sandboxes.py

Closes https://github.com/DIRACGrid/diracx/issues/353

fix(db): assigning non existing sandbox or multiple times the same sandbox

---

diracx-db/src/diracx/db/sql/utils/base.py
diracx-db/src/diracx/db/sql/utils/functions.py
diracx-routers/pyproject.toml
diracx-routers/tests/test_job_manager.py

Closes https://github.com/DIRACGrid/diracx/issues/341
Note: 
- I disable `inherit_cache` in `date_trunc` because I had weird results when calling the `search` endpoint multiple times in a row. 
- The `time_resolution` does not seem to be part of the cached keys and whatever is the first `time_resolution` to be used becomes the "reference" in subsequent calls.
Example:
```sql
WHERE strftime(?, "Jobs"."SubmissionTime") = ?) AS anon_1
```
Here `?` seems to be replaced with the first cached value instead of the one we want to use.  
- I haven't found an easy way to include the `time_resolution` parameter in the cache keys, but my knowledge of `sqlalchemy` is very limited, and I might have overlooked something. 
- If you want to easily reproduce the issue, you can just switch `inherit_cache` …

fix(db): submission datetime

---

diracx-logic/src/diracx/logic/jobs/query.py
diracx-logic/src/diracx/logic/jobs/status.py
diracx-routers/src/diracx/routers/jobs/status.py
diracx-routers/tests/jobs/test_status.py

feat: patch job metadata endpoint

---

docs/CODING_CONVENTION.md
docs/README.md

Continuation of https://github.com/DIRACGrid/diracx/pull/410... With a fresh branch.
- Moving the part from `/docs/README.md` to `/docs/CODING_CONVENTION.md`
- Coding convention documentation restructured : from sections to a table
- Adding clear text around the instructions
- In `/docs/README.md`, changing the database classes path

doc: Moving the coding convention documentation and fixing the db location

---

requirements-dev.txt

Added a missing module to `requirements-dev.txt` that could lead to errors in `pytest`.

fix: Adding missing logic to requirements

---

diracx-db/src/diracx/db/sql/sandbox_metadata/db.py
diracx-db/tests/jobs/test_sandbox_metadata.py
diracx-routers/src/diracx/routers/jobs/access_policies.py
diracx-routers/src/diracx/routers/jobs/sandboxes.py
diracx-routers/tests/jobs/test_wms_access_policy.py

From #13 : "Implement sandbox permissions for downloading"
- a method getting sandbox owner info from SBOwnersDB
- ensure SandboxAccessPolicy verify the sandbox owner infos for read and query actions.

feat: Ensure SBAccessPolicy verifies the user owns the sandbox

---

diracx-cli/src/diracx/cli/auth.py

Found out using the dirac cli `dirac login`: 
```
│ /home/npigoux/DIRAC/diracx/diracx-cli/src/diracx/cli/auth.py:26 in               │
│ installation_metadata                                                            │
│                                                                                  │
│    23                                                                            │
│    24 async def installation_metadata():                                         │
│    25 │   async with DiracClient() as api:                                       │
│ ❱  26 │   │   return await api.well_known.installation_metadata()                │
│    27                                                                            │
│    28 …
```

fix: naming of the client well_known get installation metadata

---

diracx-logic/src/diracx/logic/auth/token.py
diracx-routers/src/diracx/routers/access_policies.py
diracx-routers/src/diracx/routers/auth/token.py
diracx-routers/tests/auth/test_legacy_exchange.py
diracx-routers/tests/auth/test_standard.py
diracx-testing/src/diracx/testing/utils.py

- getting a new access token through the `/token` endpoint using a refresh token obtained from a legacy exchange now returns the exact same refresh token (no rotation anymore)
- a new refresh token obtained through the `/token` endpoint using a general refresh token (rotation) will now have the same expiration date as the provided refresh token (approximately, is it a problem?)

fix: legacy_exchange should not rotate tokens

---

diracx-routers/src/diracx/routers/otel.py

Adding resource (`service_name` and `service_instance_id`) to the metrics.
Could potentially solve issues we have when multiple pods are sending metric values in parallel.
It works only if the `opentelemetry-collector.config.exporters.prometheus.resource_to_telemetry_conversion` is enabled in the helm chart.
We are trying to test the solution in LHCb context but it's not that straightforward.

feat: add service instance id and name to the metrics

---

diracx-db/src/diracx/db/os/job_parameters.py
diracx-db/tests/opensearch/test_search.py

This is causing cypress tests to fail in https://github.com/DIRACGrid/diracx-web/pull/327 due to the job status change failing when killing a job as it sets a parameter in the JobParameterDB with vo=`diracAdmin`, which leads to a non-lowercase index name, which opensearch dislikes.

fix (JobParametersDB): Ensure index names are lowercase in case the VO has capital letters

---

diracx-logic/src/diracx/logic/auth/utils.py
diracx-routers/src/diracx/routers/auth/management.py
diracx-routers/tests/auth/test_standard.py

Changed the error handling in the fixed logout router: [in these lines](https://github.com/Robin-Van-de-Merghel/diracx/blob/4c72d9a5225d6e8fb930d14fafe808c3261f94a4/diracx-logic/src/diracx/logic/auth/utils.py#L193-L205).
This led if the token is badly shaped to a crash in `verify_dirac_access_token`, because we catch only `JoseError`, but we raise `ValueError` which is not caught.
I found this bug doing [CI in another PR](https://github.com/DIRACGrid/diracx/actions/runs/14658762686/job/41138418074?pr=421), but we did not catch this elsewhere because this is not tested everywhere.

[HotFix]: Bad error handling can lead to a 500 error

---

pyproject.toml

[PP003](https://learn.scientific-python.org/development/guides/packaging-classic#PP003): Does not list wheel as a build-dep
Do not include "wheel" in your build-system.requires, setuptools does this via PEP 517 already. Setuptools will also only require this for actual wheel builds, and might have version limits.
[PP302](https://learn.scientific-python.org/development/guides/pytest#PP302): Sets a minimum pytest to at least 6
Must have a minversion=, and must be at least 6 (first version to support pyproject.toml configuration).
[tool.pytest.ini_options]
minversion = "7"
[PP304](https://learn.scientific-python.org/development/guides/pytest#PP304): Sets the log level in pytest
log_cli_level should be set. This will allow logs to be displayed on failures.
[tool.pytest.ini_options] …

feat: address pyproject.toml suggestions from repo review

---

diracx-core/src/diracx/core/exceptions.py

Fixed the current errors (bad use of f-strings, wrong refactoring, migrating to `RuntimeError`).
In this PR, I can also add something to avoid duplication:
```py
class GenericError(DiracError):
pattern = "Error: %s"
def __init__(self, data: dict[str, str], detail: str | None = None):
self.data = data
self.detail = detail
parts = [f"({key}: {value})" for key, value in data.items()]
message = pattern % {' '.join(parts)}
if detail:
pattern += f": {detail}"
super().__init__(message)
```
The idea: you extend this class with your proper pattern, to avoid duplicating. It also helps having a flexibility on the parameters we give to the error. Example:
```py
class PilotNotFoundError(GenericError):
pattern = "Pilot %s not found"
raise MyPersonalizedError(data={
"pilot_stamp": "a-stamp"
})
raise …
```

Fixed current exceptions in Dirac Core

---

diracx-routers/src/diracx/routers/factory.py

It's needed if we want to go to next/previous page from a local instance of `diracx-web` (launched through `npm run dev`)

feat: expose Content-Range response header for diracx-web running locally

---

diracx-routers/src/diracx/routers/utils/users.py
diracx-routers/tests/auth/test_standard.py

```
File "/diracx_source/diracx/diracx-routers/src/diracx/routers/utils/users.py", line 92, in verify_dirac_access_token
claims = read_token(
^^^^^^^^^^^
File "/diracx_source/diracx/diracx-logic/src/diracx/logic/auth/utils.py", line 204, in read_token
claims_requests.validate(token.claims)
File "/opt/conda/lib/python3.11/site-packages/joserfc/rfc7519/registry.py", line 51, in validate
func(value)
File "/opt/conda/lib/python3.11/site-packages/joserfc/rfc7519/registry.py", line 111, in validate_exp
raise ExpiredTokenError()
```

[BUG] fix: Fixed verify_token error

---

diracx-core/src/diracx/core/s3.py
diracx-db/src/diracx/db/sql/sandbox_metadata/db.py
diracx-logic/src/diracx/logic/jobs/sandboxes.py

This pull request introduces enhancements to type safety, database query logic, and sandbox cleanup functionality across multiple modules. The most important changes include the introduction of the `TypedDict` type for S3 objects, improvements to database query conditions, and the addition of concurrency control for sandbox cleanup operations.
* [`diracx-core/src/diracx/core/s3.py`](diffhunk://#diff-b1e7805875c076b980fe06e23ddc6e9127bc6de5015e6e99a6c5134a839522abR21-R27): Added a `TypedDict` named `S3Object` to define the structure of S3 object dictionaries, improving type safety in `s3_bulk_delete_with_retry`. [[1]](diffhunk://#diff-b1e7805875c076b980fe06e23ddc6e9127bc6de5015e6e99a6c5134a839522abR21-R27) [[2]](diffhunk://#diff-b1e7805875c076b980fe06e23ddc6e9127bc6de5015e6e99a6c5134a839522 …

Removing sandboxes which are no longer assigned

---

diracx-testing/pyproject.toml

The new version `1.1.0` is breaking the CI: https://github.com/DIRACGrid/diracx/actions/runs/16345163597/job/46176893538?pr=469
Probably because `resolve_fixtures_hack` is "too fragile"...
https://github.com/DIRACGrid/diracx/blob/727e8ce97a5e1a1ab1469747a702a5f7b35d5418/diracx-db/tests/opensearch/test_search.py#L42-L99

fix: freeze pytest-asyncio

---

diracx-logic/src/diracx/logic/jobs/query.py
diracx-routers/src/diracx/routers/jobs/query.py

Currently users with `JOB_ADMINISTRATORS` properties cannot see jobs of other users because of: https://github.com/aldbr/diracx/blob/a37ff0db0dab93ce90d44938310ba35ed1f1cbd9/diracx-logic/src/diracx/logic/jobs/query.py#L49-L60
I don't know if this is the best way of handling that problem, because I see some `TODO` notes like `# TODO: Apply all the job policy stuff properly using user_info`.
I am coming with some unit tests soon.

fix: job admins cannot see jobs from other users

---

diracx-testing/src/diracx/testing/client_generation.py

Fixes a bug on macOS where the directory would not be created causing the client generation to fail.

fix: check AUTOREST_HOME directory is created if it doesn't exist

---

diracx-logic/src/diracx/logic/jobs/query.py

Very similar to https://github.com/DIRACGrid/diracx/pull/469
Problems to get the summaries, preventing us from getting suggestions in the search bar in `diracx-web`.

fix: job admins cannot get summaries including jobs from other users

---

.github/workflows/deployment.yml
.github/workflows/update_chart_version.py

- Add update-charts job to deployment workflow triggered on releases
- Add Python script to handle chart version bumping logic
- Automatically update Chart.yaml appVersion and version fields
- Update values.yaml image tags to match DiracX version
- Push changes to charts repo main branch and create version tags
- Include pre-commit hook execution to maintain chart documentation
The automation ensures DiracX charts stay synchronized with DiracX releases without manual intervention.

feat(ci): add automatic chart version bumping on DiracX releases

---

diracx-cli/src/diracx/cli/auth.py
diracx-client/src/diracx/client/_generated/aio/operations/_operations.py
diracx-client/src/diracx/client/_generated/models/__init__.py
diracx-client/src/diracx/client/_generated/models/_models.py
diracx-client/src/diracx/client/_generated/operations/_operations.py
diracx-client/src/diracx/client/patches/auth/aio.py
diracx-client/src/diracx/client/patches/auth/common.py
diracx-client/src/diracx/client/patches/auth/sync.py
diracx-core/src/diracx/core/models.py
diracx-logic/src/diracx/logic/auth/management.py
diracx-routers/src/diracx/routers/auth/management.py
diracx-routers/tests/auth/test_standard.py
extensions/gubbins/gubbins-client/src/gubbins/client/_generated/aio/operations/_operations.py
extensions/gubbins/gubbins-client/src/gubbins/client/_generated/models/__init__.py
extensions/gubbins/gubbins-client/src/gubbins/client/_generated/models/_models.py
extensions/gubbins/gubbins-client/src/gubbins/client/_generated/operations/_operations.py

Aims at solving https://github.com/DIRACGrid/diracx-web/issues/339
Made with @trnkv
Goes with https://github.com/DIRACGrid/diracx-web/pull/421

fix: token revoke endpoint parameters
