DIRACGrid/diracx

- run_local.sh
use correct environment variable in `run_local.sh`
> CONFIG_URL in run_local.sh

- .github/workflows/integration.yml
- .github/workflows/main.yml
- .gitignore
- .gitlab-ci.yml
- Dockerfile
- docs/README.md
- environment.yml
- pyproject.toml
- src/diracx/__init__.py
- src/diracx/cli/__init__.py
- src/diracx/cli/jobs.py
- src/diracx/client/operations/_patch.py
- src/diracx/core/preferences.py
- src/diracx/db/jobs/db.py
- src/diracx/db/jobs/schema.py
- src/diracx/db/utils.py
- src/diracx/routers/job_manager/__init__.py
- tests/.dirac-ci-config.yaml
- tests/conftest.py
- tests/db/test_jobDB.py
- tests/routers/test_job_manager.py
Main thing here is:
* use the actual preferences for getting the diracx url
* run the DIRAC integration tests against DiracX. Of course it fails !  But we make it always pass for now
Needs https://github.com/DIRACGrid/DIRAC/pull/7143 to be merged
> Dirac integration tests

- src/diracx/db/jobs/db.py
> Make jobloggingdb compatible with mysql

- .coveragerc
- src/diracx/db/os/utils.py
- src/diracx/db/sql/utils.py
- tests/db/opensearch/conftest.py
- tests/db/opensearch/test_index_template.py
- tests/db/opensearch/test_search.py
> Implement OpenSearch DB search method

- src/diracx/cli/__init__.py
- src/diracx/client/aio/operations/_operations.py
- src/diracx/client/models/__init__.py
- src/diracx/client/models/_models.py
- src/diracx/client/operations/_operations.py
- src/diracx/routers/auth.py
- src/diracx/routers/well_known.py
Also includes a crude `dirac whoami` command.
> Add userinfo endpoint

- environment.yml
- src/diracx/core/models.py
- src/diracx/core/s3.py
- tests/core/test_s3.py
Ready for review but left as draft as it builds upon #113
> Add S3 utility functions

- .pre-commit-config.yaml
- environment.yml
- setup.cfg
- src/diracx/core/s3.py
- src/diracx/routers/job_manager/sandboxes.py
- tests/conftest.py
- tests/core/test_s3.py
Needs #119. Only the last commit is unique to this PR.
> Use aiobotocore

- src/diracx/db/sql/jobs/db.py
- src/diracx/db/sql/jobs/schema.py
To be merged once https://github.com/DIRACGrid/DIRAC/pull/7215 get merged
> Add vo column in jobs db

- .github/workflows/main.yml
- src/diracx/cli/internal/legacy.py
- src/diracx/client/_patch.py
- src/diracx/client/aio/_patch.py
- src/diracx/client/aio/operations/_patch.py
- src/diracx/client/operations/_operations.py
- src/diracx/client/operations/_patch.py
- src/diracx/core/preferences.py
- src/diracx/db/sql/jobs/db.py
- src/diracx/routers/__init__.py
- src/diracx/routers/auth.py
- src/diracx/routers/fastapi_classes.py
- src/diracx/routers/well_known.py
- tests/cli/test_login.py
- tests/client/test_regenerate.py
- tests/conftest.py
- tests/db/opensearch/test_connection.py
- tests/routers/auth/test_legacy_exchange.py
- tests/routers/auth/test_standard.py
- tests/routers/jobs/test_sandboxes.py
- tests/routers/test_config_manager.py
- tests/routers/test_generic.py
- tests/routers/test_job_manager.py
Introduce the necessary components to include `diracx-web` in `diracx-charts`.
> feat: include components to communicate with the webapp

- src/diracx/routers/auth.py
- tests/routers/auth/test_legacy_exchange.py
> Support expires_minutes on /api/auth/legacy-exchange

- src/diracx/client/models/_models.py
- src/diracx/db/sql/jobs/db.py
- src/diracx/routers/job_manager/__init__.py
- tests/routers/test_job_manager.py
This adds a distinct option to the job search interface (and db class) plus a test; I hope that's what you had in mind for #134?
Closes #134 (maybe).
> Add distinct option to job search

- Dockerfile
- dockerEntrypoint.sh
- dockerMicroMambaEntrypoint.sh
> Use diracx/server-base:latest as a basis of the docker image

- src/diracx/core/utils.py
Required for https://github.com/DIRACGrid/DIRAC/pull/7261 which is part of https://github.com/DIRACGrid/diracx/issues/132
> Add serialize_credentials method for DIRAC to use when writing proxies

- security_model.md
> Add security model

- docs/VERSIONING.md
closes https://github.com/DIRACGrid/diracx/issues/145
> Document packaging and versioning

- diracx-api/pyproject.toml
- diracx-cli/pyproject.toml
- diracx-cli/src/diracx/cli/__init__.py
- diracx-cli/src/diracx/cli/internal/__init__.py
- diracx-cli/tests/test_internal.py
- diracx-client/pyproject.toml
- diracx-client/tests/test_regenerate.py
- diracx-core/pyproject.toml
- diracx-core/src/diracx/core/extensions.py
- diracx-core/tests/test_extensions.py
- diracx-core/tests/test_s3.py
- diracx-core/tests/test_secrets.py
- diracx-db/pyproject.toml
- diracx-db/src/diracx/db/os/utils.py
- diracx-db/src/diracx/db/sql/jobs/db.py
- diracx-routers/pyproject.toml
- diracx-routers/src/diracx/routers/job_manager/__init__.py
- diracx-routers/src/diracx/routers/job_manager/sandboxes.py
- diracx-routers/tests/auth/test_legacy_exchange.py
- diracx-routers/tests/auth/test_standard.py
- diracx-routers/tests/jobs/test_sandboxes.py
- diracx-routers/tests/test_config_manager.py
- diracx-routers/tests/test_generic.py
- diracx-routers/tests/test_job_manager.py
- diracx-testing/pyproject.toml
- diracx-testing/src/diracx/testing/__init__.py
- pyproject.toml
This makes the unit tests go from 90 seconds to 9 seconds.
> Faster unit tests

- diracx-core/src/diracx/core/settings.py
- diracx-db/src/diracx/db/sql/auth/db.py
- diracx-db/src/diracx/db/sql/auth/schema.py
- diracx-routers/src/diracx/routers/auth.py
- diracx-routers/tests/auth/test_standard.py
- diracx-testing/src/diracx/testing/__init__.py
- run_local.sh
Aims at solving 2 points from https://github.com/DIRACGrid/diracx/issues/30
Note to myself: Once the PR is approved, I would need to create a PR in `diracx-charts` to add the `state_key` as a Kubernetes secret.
> Hash & Encrypt: auth module

- diracx-core/src/diracx/core/config/__init__.py
- diracx-core/src/diracx/core/config/schema.py
- diracx-core/tests/test_config_source.py
closes https://github.com/DIRACGrid/diracx/issues/230
> Create ConfigSource for remote git repository

- diracx-cli/src/diracx/cli/internal/legacy.py
Needs https://github.com/DIRACGrid/diracx-charts/pull/105
> feat(cli): update helm values in internal legacy CLI

- docs/ROADMAP.MD
This will be followed later by epics and precise issues
> Add roadmap

- diracx-db/src/diracx/db/sql/job_logging/db.py
- diracx-db/src/diracx/db/sql/utils/job.py
- diracx-db/tests/jobs/test_jobLoggingDB.py
- diracx-routers/src/diracx/routers/jobs/query.py
- diracx-routers/tests/test_job_manager.py
> fix #351: enable query of job logging DB via search endpoint

- diracx-db/src/diracx/db/sql/job/db.py
- diracx-db/src/diracx/db/sql/utils/job.py
- diracx-routers/tests/test_job_manager.py
> Fix job attribute update to account for mismatching columns between rows

- diracx-core/src/diracx/core/exceptions.py
- diracx-db/src/diracx/db/sql/sandbox_metadata/db.py
- diracx-db/tests/jobs/test_sandbox_metadata.py
- diracx-routers/pyproject.toml
- diracx-routers/src/diracx/routers/jobs/sandboxes.py
Closes https://github.com/DIRACGrid/diracx/issues/358
> fix(diracx-routers): remove sqlalchemy dependency

- .pre-commit-config.yaml
- diracx-core/src/diracx/core/models.py
- diracx-routers/src/diracx/routers/utils/users.py
> fix: updated pre-commit, and fixed false positives

- diracx-routers/src/diracx/routers/jobs/submission.py
- diracx-routers/tests/test_job_manager.py
Closes https://github.com/DIRACGrid/diracx/issues/354
> fix(routers): status 500 when malformed jdls are given

- diracx-cli/tests/legacy/cs_sync/integration_test.cfg
- diracx-cli/tests/legacy/cs_sync/integration_test.yaml
- diracx-cli/tests/legacy/cs_sync/integration_test_secret.cfg
(also using this to test failures in integration tests)
> fix: remove DIRAC setup

- diracx-core/src/diracx/core/config/sources.py
logs failed `git pull` attempts
use `git clone [--branch ...] repo [location]` instead of `git clone ... && git checkout ...`
also fixed a typo
> fix: Log failed CS git pull attempts

- diracx-routers/src/diracx/routers/factory.py
- diracx-routers/src/diracx/routers/otel.py
Based on:
- https://github.com/DIRACGrid/diracx/pull/458
- https://github.com/DIRACGrid/diracx-charts/pull/145
> feat: record otel metrics (duration of the requests)

- diracx-core/src/diracx/core/config/sources.py
- diracx-core/src/diracx/core/exceptions.py
- diracx-core/src/diracx/core/utils.py
- diracx-routers/src/diracx/routers/factory.py
- diracx-routers/src/diracx/routers/health/probes.py
- diracx-routers/tests/health/test_probes.py
- diracx-testing/src/diracx/testing/utils.py
This pull request to `diracx-core` and `diracx-routers` includes significant changes to caching mechanisms, exception handling, and configuration loading. The most important changes include the introduction of a two-level cache system, updates to abstract classes and methods, and improvements to exception handling and health check endpoints.
* [`diracx-core/src/diracx/core/config/sources.py`](diffhunk://#diff-905672a687fb25908ececb39cb6137034a5127e5e2fa46ec97e4a03a1e6bfb52L20-R33): Introduced `TwoLevelCache` for caching configuration revisions and content, replacing the previous single-level caches. This new cache system has both soft and hard TTLs to improve data freshness and reduce latency. [[1]](diffhunk://#diff-905672a687fb25908ececb39cb6137034a5127e5e2fa46ec97e4a03a1e6bfb52L20-R33) …
> Improve caching logic around ConfigSource

- diracx-db/src/diracx/db/sql/job_logging/db.py
- diracx-db/src/diracx/db/sql/job_logging/schema.py
- diracx-db/tests/jobs/test_job_logging_db.py
- diracx-logic/src/diracx/logic/jobs/status.py
- diracx-routers/tests/jobs/test_status.py
Fixes #476
Fixes the issue with the last sign of life being in the future
> Job logging fixes

- diracx-logic/src/diracx/logic/jobs/status.py
> fix: ensure HeartBeatTime is updated from new heartbeat logic

- diracx-routers/tests/jobs/test_status.py
Test that job commands are set and passed back correctly on the next heartbeat, after killing a job
> feat: test job commands are set after killing a job

- diracx-core/src/diracx/core/exceptions.py
- diracx-core/src/diracx/core/settings.py
- diracx-logic/src/diracx/logic/auth/token.py
- diracx-routers/src/diracx/routers/auth/management.py
- diracx-routers/src/diracx/routers/auth/token.py
- diracx-routers/src/diracx/routers/utils/users.py
- diracx-routers/tests/auth/test_standard.py
Aims at fixing https://github.com/DIRACGrid/diracx/actions/runs/15248175086/job/42878643647?pr=421#step:12:1222
> fix: joserfc breaking changes

- diracx-cli/pyproject.toml
- pixi.toml
See https://github.com/fastapi/typer/discussions/1215
> Revert workaround typer 1215

- diracx-core/src/diracx/core/settings.py
Last step of https://github.com/DIRACGrid/diracx/pull/499
Closes https://github.com/DIRACGrid/diracx/issues/521
> feat(auth): remove single key support

- diracx-client/src/diracx/client/_generated/models/_enums.py
- diracx-client/src/diracx/client/_generated/models/_models.py
- diracx-core/src/diracx/core/models.py
- diracx-db/src/diracx/db/sql/utils/base.py
- diracx-db/tests/jobs/test_job_db.py
- extensions/gubbins/gubbins-client/src/gubbins/client/_generated/models/_enums.py
- extensions/gubbins/gubbins-client/src/gubbins/client/_generated/models/_models.py
I've added two new operators for the job search. These operators come with tests.
> New operators for job db

- diracx-routers/src/diracx/routers/jobs/access_policies.py
Linked to https://github.com/DIRACGrid/DIRAC/issues/8273
> fix: Fixed WMS to remove JOB_ADMINISTRATOR from pilot properties

- diracx-routers/src/diracx/routers/factory.py
> fix: add CORS origins for https:// local dev instances

- diracx-core/src/diracx/core/config/schema.py
- diracx-logic/src/diracx/logic/jobs/utils.py
fixes https://github.com/DIRACGrid/diracx/issues/655
> fix InputDataPolicy schema definition
